Minor improvements and bugfixes - Added README.md - Improved error handling - Output readability - Helper tools check

diff --git a/asn b/asn
--- a/asn
+++ b/asn
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 ################################################################################################################
 # ---------------------------------------------------------------------------
@@ -16,7 +16,7 @@
 
 WhoisASN(){
         found_asname=$(whois -h whois.cymru.com " -f -w -c -p as$1" | sed -e 's/\ *|\ */|/g' | awk -F '[|]' {'print $3'})
-        printf "${red}[AS$1] ${green}$found_asname\n${white}"
+        printf "\n${red}[AS$1] ${green}$found_asname\n${white}"
 }
 
 WhoisIP(){
@@ -31,6 +31,8 @@ LookupASNAndRouteFromIP(){
         found_asn=$(echo $output | awk -F'[|]' {'print $1'})
         found_asname=$(echo $output | awk -F'[|]' {'print $4'})
         found_route=$(echo $output | awk -F'[|]' {'print $3'})
+        [[ "$found_asname" == "NA" ]] && found_asname=""
+        [[ "$found_route" == "NA" ]] && found_route=""
 }
 
 ResolveHostnameToIPList(){
@@ -64,18 +66,28 @@ if [[ $# -ne 1 ]]; then
         exit 1
 fi
 
+# Check prerequisites
+if [ -z $(command -v "whois") ]; then
+        echo -e "\n${red}ERROR: ${white}program '${red}whois${white}' not found on this system.\nPlease install it (for example with ${green}sudo apt install whois${white} on Debian-based linux distributions)"
+        exit 1
+fi
+if [ -z $(command -v "host") ]; then
+        echo -e "\n${red}ERROR: ${white}program '${red}host${white}' not found on this system.\nPlease install it (for example with ${green}sudo apt install bind9-host${white} on Debian-based linux distributions)"
+        exit 1
+fi
+
 input=$(echo $1 | sed -e 's/\/.*//g' | grep -Eo $ipv4v6regex)
 if [ -z "$input" ]; then
         # Input is not an IP Address. Check if it is a number (ASN)
         asn=$(echo $1 | sed -e 's/[a|A][s|S]//g' | grep -E "^[0-9]*$")
         if [ -z "$asn" ]; then
                 # Input is not an ASN either. Consider it a hostname and try to resolve it.
-                echo -e -n "${blue}Resolving \"$1\"... "
+                echo -e -n "\n${blue}Resolving \"$1\"... "
                 ip=$(ResolveHostnameToIPList $1)
                 if [ -z "$ip" ]; then
-                        echo -e "\e[97m\e[101mError: unable to resolve hostname\e[39m\e[49m"
+                        echo -e "\e[30m\e[101mError: unable to resolve hostname\e[39m\e[49m"
                         tput sgr0
-                        exit
+                        exit 1
                 fi
                 numips=$(echo "$ip" | wc -l)
                 [[ $numips = 1 ]] && s="" || s="es"
@@ -103,11 +115,11 @@ else
         # Input is an IP address
         LookupASNAndRouteFromIP $input
         if [ -z "$found_asname" ] && [ -z "$found_route" ]; then
-                echo -e "\e[97m\e[101mError: no data found for $input\e[39m\e[49m"
+                echo -e "\n\e[30m\e[101mError: no data found for $input\e[39m\e[49m"
                 tput sgr0
                 exit
         fi
-        echo -e "${green}1 IP address found:\e[39m"
+        echo -e "\n${green}1 IP address found:\e[39m"
         WhoisIP $input
         tput sgr0
         exit
